[project]
name = "spotify-mcp-server"
version = "0.1.0"
description = "A simple server to control Spotify using MCP"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.7.1",
    "spotipy>=2.25.1",
    "mcp==1.7.1",
]
